ACC = 0
ACC += 72
print(chr(ACC), end="")
ACC += 29
print(chr(ACC), end="")
ACC += 7
print(chr(ACC), end="")
print(chr(ACC), end="")
ACC += 3
print(chr(ACC), end="")
ACC -= 67
print(chr(ACC), end="")
ACC -= 12
print(chr(ACC), end="")
ACC += 55
print(chr(ACC), end="")
ACC += 24
print(chr(ACC), end="")
ACC += 2
print(chr(ACC), end="")
ACC -= 6
print(chr(ACC), end="")
ACC -= 8
print(chr(ACC), end="")
ACC -= 67
print(chr(ACC), end="")
